### PR TITLE
Use redis to cache retrieved FHIR resources

### PR DESCRIPTION
**Pull request by erikwiffin**

### CODE REVIEW

**Comment by jmandel** [comment]
Wow. I was expecting, like, a python dict ;-)

**Comment by erikwiffin** [comment]
I tried a python dict at first, and I think the resetting of state between tests was causing issues. We already had redis running though, so hooking that up was pretty easy.

**Comment by jmandel** [comment]
Wait, just so I understand what happened with the dict: do you mean
resetting the cache between features of a single run was causing trouble?
(Why would the cache be reset between features of a single run?)

**Comment by jmandel** [comment]
BTW, this is a major speed improvement on some of the servers with large
data volume!

**Comment by erikwiffin** [comment]
The way that behave determines feature/scenario scope was reseting the cache dict each run. It basically made a copy of the cache, gave it a step, the step filled the copy, and then the copy was thrown away.

**Pull request merged**
