### PR TITLE
sync-for-science/tracking#175 - Add test to ensure returned patient I…

### PR DESCRIPTION
**Pull request by abjonnes**
…D matches the queried patient ID

### CODE REVIEW

**Comment by mtmcduffie** [comment]
I think it looks good. If it ever becomes a problem we could check if the Patient ID we get from the Oauth exchange is the same as the one we expect from our own config file, but things would have to be seriously wrong if there wasn't harmony between those three points.

Approved!

**Comment by jmandel** [comment]
Oh, that's a really good point @mtmcduffie  -- why wouldn't we check all three? In our typical deployment scenario we should be relying entirely on the value from the OAuth exchange...

**Comment by jmandel** [comment]
Thanks! Perhaps this could be a second, separate test like: 

* $OAuth response must include a patient" (i.e. so if we use an override value from config, it still works but complains loudly with a red mark on the scorecard)

**Comment by abjonnes** [comment]
I factored out two common asserts to reduce code duplication.

**Comment by jmandel** [comment]
Nice -- I like the DRYness, and also the readability improvement. Re: checking patient id in OAuth response vs supplied in config, would you prefer to address this in a separate PR? (I think that could make sense, since currently the value is clobbered when we read the OAuth response, so we'd need to stash it somewhere in order to evaluate the comparison...)

**Comment by abjonnes** [comment]
Yeah I think a separate PR for that makes more sense. I'll work on that as well

**Comment by jmandel** [comment]
cool -- I'd say go ahead and merge this one then whenever you're ready!

**Pull request merged**
