### PR TITLE
sync-for-science/tracking#158 - Updating code set validation.

### PR DESCRIPTION
**Pull request by mtmcduffie**

### CODE REVIEW

**Comment by mtmcduffie** [comment]
@jmandel - Do the body weight/SO2 changes ring any bells? Didn't see anything in the google group about us wanting a different value set for those..

**Comment by jmandel** [comment]
Wait is this removing body weight?

**Comment by mtmcduffie** [comment]
That code doesn't appear in - http://www.fhir.org/guides/argonaut/r2/ValueSet-observation-ccdavitalsignresult.json.html

**Comment by mtmcduffie** [comment]
Err, it defines it as - 29463-7

**Comment by jmandel** [comment]
Tree can you compare with the list of codes in the current u.s. Core at http://hl7.org/fhir/valueset-observation-vitalsignresult.html so we understand any gaps?

**Comment by mtmcduffie** [comment]
Codes in list you linked not in new list

1. 8478-0 Mean blood pressure
2. 85354-9 (b)lood pressure panel with all children optional
3. 85353-1 Vital signs, weight, height, head circumference, oxygen saturation & BMI panel

New codes not in list you linked

1. 8716-3 (https://s.details.loinc.org/LOINC/8716-3.html)
2. 55284-4 (https://s.details.loinc.org/LOINC/55284-4.html)

**Comment by mtmcduffie** [comment]
Final Offer - Validate combined set of lists.

**Comment by jmandel** [comment]
Let's use the union for now...

**Comment by mtmcduffie** [comment]
@jmandel - Updated to have union of codes.

**Pull request merged**
